/**
 * @deepika27-alt/ui — Tailwind CSS Preset
 *
 * This preset maps Tailwind theme values directly to the dynamic CSS custom properties
 * generated from the library's design tokens.
 */
module.exports = {
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'var(--ui-color-primary-50)',
          100: 'var(--ui-color-primary-100)',
          200: 'var(--ui-color-primary-200)',
          300: 'var(--ui-color-primary-300)',
          400: 'var(--ui-color-primary-400)',
          500: 'var(--ui-color-primary-500)',
          600: 'var(--ui-color-primary-600)',
          700: 'var(--ui-color-primary-700)',
          800: 'var(--ui-color-primary-800)',
          900: 'var(--ui-color-primary-900)',
        },
        neutral: {
          50: 'var(--ui-color-neutral-50)',
          100: 'var(--ui-color-neutral-100)',
          200: 'var(--ui-color-neutral-200)',
          300: 'var(--ui-color-neutral-300)',
          400: 'var(--ui-color-neutral-400)',
          500: 'var(--ui-color-neutral-500)',
          600: 'var(--ui-color-neutral-600)',
          700: 'var(--ui-color-neutral-700)',
          800: 'var(--ui-color-neutral-800)',
          900: 'var(--ui-color-neutral-900)',
        },
        success: {
          50: 'var(--ui-color-success-50)',
          100: 'var(--ui-color-success-100)',
          200: 'var(--ui-color-success-200)',
          300: 'var(--ui-color-success-300)',
          400: 'var(--ui-color-success-400)',
          500: 'var(--ui-color-success-500)',
          600: 'var(--ui-color-success-600)',
          700: 'var(--ui-color-success-700)',
          800: 'var(--ui-color-success-800)',
          900: 'var(--ui-color-success-900)',
        },
        warning: {
          50: 'var(--ui-color-warning-50)',
          100: 'var(--ui-color-warning-100)',
          200: 'var(--ui-color-warning-200)',
          300: 'var(--ui-color-warning-300)',
          400: 'var(--ui-color-warning-400)',
          500: 'var(--ui-color-warning-500)',
          600: 'var(--ui-color-warning-600)',
          700: 'var(--ui-color-warning-700)',
          800: 'var(--ui-color-warning-800)',
          900: 'var(--ui-color-warning-900)',
        },
        danger: {
          50: 'var(--ui-color-danger-50)',
          100: 'var(--ui-color-danger-100)',
          200: 'var(--ui-color-danger-200)',
          300: 'var(--ui-color-danger-300)',
          400: 'var(--ui-color-danger-400)',
          500: 'var(--ui-color-danger-500)',
          600: 'var(--ui-color-danger-600)',
          700: 'var(--ui-color-danger-700)',
          800: 'var(--ui-color-danger-800)',
          900: 'var(--ui-color-danger-900)',
        },
        info: {
          50: 'var(--ui-color-info-50)',
          100: 'var(--ui-color-info-100)',
          200: 'var(--ui-color-info-200)',
          300: 'var(--ui-color-info-300)',
          400: 'var(--ui-color-info-400)',
          500: 'var(--ui-color-info-500)',
          600: 'var(--ui-color-info-600)',
          700: 'var(--ui-color-info-700)',
          800: 'var(--ui-color-info-800)',
          900: 'var(--ui-color-info-900)',
        },
      },
      borderRadius: {
        none: 'var(--ui-border-radius-none)',
        sm: 'var(--ui-border-radius-sm)',
        md: 'var(--ui-border-radius-md)',
        lg: 'var(--ui-border-radius-lg)',
        xl: 'var(--ui-border-radius-xl)',
        '2xl': 'var(--ui-border-radius-2xl)',
        full: 'var(--ui-border-radius-full)',
      },
      spacing: {
        1: 'var(--ui-spacing-1)',
        2: 'var(--ui-spacing-2)',
        3: 'var(--ui-spacing-3)',
        4: 'var(--ui-spacing-4)',
        5: 'var(--ui-spacing-5)',
        6: 'var(--ui-spacing-6)',
        7: 'var(--ui-spacing-7)',
        8: 'var(--ui-spacing-8)',
        9: 'var(--ui-spacing-9)',
        10: 'var(--ui-spacing-10)',
        11: 'var(--ui-spacing-11)',
        12: 'var(--ui-spacing-12)',
        13: 'var(--ui-spacing-13)',
        14: 'var(--ui-spacing-14)',
        15: 'var(--ui-spacing-15)',
        16: 'var(--ui-spacing-16)',
      },
      fontFamily: {
        sans: 'var(--ui-typography-font-family-sans)',
        mono: 'var(--ui-typography-font-family-mono)',
        display: 'var(--ui-typography-font-family-display)',
      },
      fontSize: {
        xs: 'var(--ui-typography-font-size-xs)',
        sm: 'var(--ui-typography-font-size-sm)',
        base: 'var(--ui-typography-font-size-base)',
        lg: 'var(--ui-typography-font-size-lg)',
        xl: 'var(--ui-typography-font-size-xl)',
        '2xl': 'var(--ui-typography-font-size-2xl)',
        '3xl': 'var(--ui-typography-font-size-3xl)',
        '4xl': 'var(--ui-typography-font-size-4xl)',
      },
      fontWeight: {
        regular: 'var(--ui-typography-font-weight-regular)',
        medium: 'var(--ui-typography-font-weight-medium)',
        semibold: 'var(--ui-typography-font-weight-semibold)',
        bold: 'var(--ui-typography-font-weight-bold)',
        extrabold: 'var(--ui-typography-font-weight-extrabold)',
      },
      lineHeight: {
        none: 'var(--ui-typography-line-height-none)',
        tight: 'var(--ui-typography-line-height-tight)',
        snug: 'var(--ui-typography-line-height-snug)',
        normal: 'var(--ui-typography-line-height-normal)',
        relaxed: 'var(--ui-typography-line-height-relaxed)',
        loose: 'var(--ui-typography-line-height-loose)',
      },
      boxShadow: {
        none: 'var(--ui-shadow-none)',
        xs: 'var(--ui-shadow-xs)',
        sm: 'var(--ui-shadow-sm)',
        md: 'var(--ui-shadow-md)',
        lg: 'var(--ui-shadow-lg)',
        xl: 'var(--ui-shadow-xl)',
        '2xl': 'var(--ui-shadow-2xl)',
      },
      transitionDuration: {
        instant: 'var(--ui-motion-duration-instant)',
        fast: 'var(--ui-motion-duration-fast)',
        normal: 'var(--ui-motion-duration-normal)',
        slow: 'var(--ui-motion-duration-slow)',
        slower: 'var(--ui-motion-duration-slower)',
      },
      transitionTimingFunction: {
        linear: 'var(--ui-motion-easing-linear)',
        easeIn: 'var(--ui-motion-easing-ease-in)',
        easeOut: 'var(--ui-motion-easing-ease-out)',
        easeInOut: 'var(--ui-motion-easing-ease-in-out)',
        spring: 'var(--ui-motion-easing-spring)',
        bounce: 'var(--ui-motion-easing-bounce)',
      },
    },
  },
  plugins: [],
};
